theme = "slick"
icons = "awesome5"
 

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{max}°"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
 
[[block]]
block = "cpu"
interval = 1
 
#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"


[[block]]
block = "pacman"
interval = 60
format = "{pacman} + {aur} = {both} updates available"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux| linux-lts| linux-zen)"
aur_command = "yay -Qu"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}°"
service = { name = "openweathermap", api_key = "6eb5d7aa49de7a3fb5dcdad64f0be388", city_id = "2646914", units = "metric" }

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %r"

 
 
