#!/bin/bash 
sudo apt update 
sudo apt install -y python3-distutils thefuck latex-mk latexmk texlive-full default-jdk openjdk-12-jdk npm tmux python3-dev python-dev python3.7-dev docker.io terraform htop powertop tlp
sudo apt upgrade -y 


pip3 install pipenv
